sudo: required
dist: trusty

language: python

python:
- '2.7'

env:
    - CKANVERSION=2.8 JAVA_OPTS="-Xms2g -Xmx2g -XX:MaxPermSize=1024m"

services:
    - redis-server
    - postgresql

install:
    - bash bin/travis-build.bash

script: bin/travis-run.sh
